name: CI

on: [push]

jobs:
  build:
    env:
      dotnet_ver: 3.1

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build linux-x64
      run: dotnet publish -c debug -r linux-x64 /p:PublishSingleFile=true
    - name: Build linux-arm
      run: dotnet publish -c debug -r linux-arm /p:PublishSingleFile=true
    - name: Build win-x64
      run: dotnet publish -c debug -r win-x64 /p:PublishSingleFile=true /p:PublishReadyToRun=true
    - name: Build osx-64
      run: dotnet publish -c debug -r osx-x64 /p:PublishSingleFile=true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: RSSBot-linux-x64-$GITHUB_SHA
        # Directory containing files to upload
        path: bin/Debug/netcoreapp$dotnet_ver/linux-x64/publish/
